# URI for database connection, leave empty if using address and credential settings directly
uri: ''
# List of MongoDB server addresses
address: [ mongo:27017 ]
# Name of the database
database: stealthX_v1
# Username for database authentication
username: stealthX
# Password for database authentication
password: stealthX123
# Authentication source for database authentication, if use root user, set it to admin
authSource: stealthX_v1
# Maximum number of connections in the connection pool
maxPoolSize: 100
# Maximum number of retry attempts for a failed database connection
maxRetry: 10
