// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "飞宏IM技术支持",
            "url": "https://github.com/liony823/chat",
            "email": "ilovecoding@foxmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/group/cancel_mute_group": {
            "post": {
                "description": "取消禁言群组",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "group"
                ],
                "summary": "取消禁言群组",
                "operationId": "cancelMuteGroup",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/group.CancelMuteGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/group.CancelMuteGroupResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/group/dismiss_group": {
            "post": {
                "description": "解散群组",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "group"
                ],
                "summary": "解散群组",
                "operationId": "dismissGroup",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/group.DismissGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/group.DismissGroupResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/group/get_group_member_list": {
            "post": {
                "description": "获取群组成员列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "group"
                ],
                "summary": "获取群组成员列表",
                "operationId": "getGroupMemberList",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/group.GetGroupMemberListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/group.GetGroupMemberListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/group/get_groups": {
            "post": {
                "description": "获取群组列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "group"
                ],
                "summary": "获取群组列表",
                "operationId": "getGroups",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/group.GetGroupsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/group.GetGroupsResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/group/kick_group": {
            "post": {
                "description": "踢出群组成员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "group"
                ],
                "summary": "踢出群组成员",
                "operationId": "kickGroupMember",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/group.KickGroupMemberReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/group.KickGroupMemberResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/group/mute_group": {
            "post": {
                "description": "禁言群组",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "group"
                ],
                "summary": "禁言群组",
                "operationId": "muteGroup",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/group.MuteGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/group.MuteGroupResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/object/auth_sign": {
            "post": {
                "description": "安全签名",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "object"
                ],
                "summary": "安全签名",
                "operationId": "authSign",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/third.AuthSignReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/third.AuthSignResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/object/complete_multipart_upload": {
            "post": {
                "description": "完成上传",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "object"
                ],
                "summary": "完成上传",
                "operationId": "completeMultipartUpload",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/third.CompleteMultipartUploadReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/third.CompleteMultipartUploadResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/object/initiate_multipart_upload": {
            "post": {
                "description": "初始化上传",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "object"
                ],
                "summary": "初始化上传",
                "operationId": "initiateMultipartUpload",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/third.InitiateMultipartUploadReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/third.InitiateMultipartUploadResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/object/part_limit": {
            "post": {
                "description": "获取分片范围",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "object"
                ],
                "summary": "获取分片范围",
                "operationId": "partLimit",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/third.PartLimitReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/third.PartLimitResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/object/part_size": {
            "post": {
                "description": "获取分片大小",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "object"
                ],
                "summary": "获取分片大小",
                "operationId": "partSize",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/third.PartSizeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/third.PartSizeResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/statistics/group/active": {
            "post": {
                "description": "获取活跃群",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "获取活跃群",
                "operationId": "getActiveGroup",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/msg.GetActiveGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/msg.GetActiveGroupResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/statistics/group/create": {
            "post": {
                "description": "获取群组统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "获取群组统计",
                "operationId": "groupCreateCount",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/group.GroupCreateCountReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/group.GroupCreateCountResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/statistics/user/active": {
            "post": {
                "description": "获取活跃用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "获取活跃用户",
                "operationId": "getActiveUser",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/msg.GetActiveUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/msg.GetActiveUserResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/statistics/user/register": {
            "post": {
                "description": "用户注册统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "用户注册统计",
                "operationId": "userRegisterCount",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserRegisterCountReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/user.UserRegisterCountResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/get_users": {
            "post": {
                "description": "获取用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户",
                "operationId": "getUsers",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.GetPaginationUsersReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/user.GetPaginationUsersResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/get_users_online_status": {
            "post": {
                "description": "获取用户在线状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户在线状态",
                "operationId": "getUsersOnlineStatus",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/msggateway.GetUsersOnlineStatusReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/msggateway.GetUsersOnlineStatusResp_SuccessResult"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/get_users_online_token_detail": {
            "post": {
                "description": "获取在线用户详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取在线用户详情",
                "operationId": "getUsersOnlineTokenDetail",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/msggateway.GetUsersOnlineStatusReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiresp.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/msggateway.SingleDetail"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apiresp.ApiResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "errCode": {
                    "type": "integer"
                },
                "errDlt": {
                    "type": "string"
                },
                "errMsg": {
                    "type": "string"
                }
            }
        },
        "group.CMSGroup": {
            "type": "object",
            "properties": {
                "groupInfo": {
                    "$ref": "#/definitions/sdkws.GroupInfo"
                },
                "groupOwnerUserID": {
                    "type": "string"
                },
                "groupOwnerUserName": {
                    "type": "string"
                }
            }
        },
        "group.CancelMuteGroupReq": {
            "type": "object",
            "properties": {
                "groupID": {
                    "type": "string"
                }
            }
        },
        "group.CancelMuteGroupResp": {
            "type": "object"
        },
        "group.DismissGroupReq": {
            "type": "object",
            "properties": {
                "deleteMember": {
                    "type": "boolean"
                },
                "groupID": {
                    "type": "string"
                }
            }
        },
        "group.DismissGroupResp": {
            "type": "object"
        },
        "group.GetGroupMemberListReq": {
            "type": "object",
            "properties": {
                "filter": {
                    "type": "integer"
                },
                "groupID": {
                    "type": "string"
                },
                "keyword": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/sdkws.RequestPagination"
                }
            }
        },
        "group.GetGroupMemberListResp": {
            "type": "object",
            "properties": {
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sdkws.GroupMemberFullInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "group.GetGroupsReq": {
            "type": "object",
            "properties": {
                "groupID": {
                    "type": "string"
                },
                "groupName": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/sdkws.RequestPagination"
                }
            }
        },
        "group.GetGroupsResp": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/group.CMSGroup"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "group.GroupCreateCountReq": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "integer"
                },
                "start": {
                    "type": "integer"
                }
            }
        },
        "group.GroupCreateCountResp": {
            "type": "object",
            "properties": {
                "before": {
                    "type": "integer"
                },
                "count": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "group.KickGroupMemberReq": {
            "type": "object",
            "properties": {
                "groupID": {
                    "type": "string"
                },
                "kickedUserIDs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "group.KickGroupMemberResp": {
            "type": "object"
        },
        "group.MuteGroupReq": {
            "type": "object",
            "properties": {
                "groupID": {
                    "type": "string"
                }
            }
        },
        "group.MuteGroupResp": {
            "type": "object"
        },
        "msg.ActiveGroup": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "group": {
                    "$ref": "#/definitions/sdkws.GroupInfo"
                }
            }
        },
        "msg.ActiveUser": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/sdkws.UserInfo"
                }
            }
        },
        "msg.GetActiveGroupReq": {
            "type": "object",
            "properties": {
                "ase": {
                    "type": "boolean"
                },
                "end": {
                    "type": "integer"
                },
                "pagination": {
                    "$ref": "#/definitions/sdkws.RequestPagination"
                },
                "start": {
                    "type": "integer"
                }
            }
        },
        "msg.GetActiveGroupResp": {
            "type": "object",
            "properties": {
                "dateCount": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "groupCount": {
                    "type": "integer"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/msg.ActiveGroup"
                    }
                },
                "msgCount": {
                    "type": "integer"
                }
            }
        },
        "msg.GetActiveUserReq": {
            "type": "object",
            "properties": {
                "ase": {
                    "type": "boolean"
                },
                "end": {
                    "type": "integer"
                },
                "group": {
                    "type": "boolean"
                },
                "pagination": {
                    "$ref": "#/definitions/sdkws.RequestPagination"
                },
                "start": {
                    "type": "integer"
                }
            }
        },
        "msg.GetActiveUserResp": {
            "type": "object",
            "properties": {
                "dateCount": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "msgCount": {
                    "type": "integer"
                },
                "userCount": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/msg.ActiveUser"
                    }
                }
            }
        },
        "msggateway.GetUsersOnlineStatusReq": {
            "type": "object",
            "properties": {
                "userIDs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "msggateway.GetUsersOnlineStatusResp_SuccessDetail": {
            "type": "object",
            "properties": {
                "connID": {
                    "type": "string"
                },
                "isBackground": {
                    "type": "boolean"
                },
                "platformID": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "msggateway.GetUsersOnlineStatusResp_SuccessResult": {
            "type": "object",
            "properties": {
                "detailPlatformStatus": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/msggateway.GetUsersOnlineStatusResp_SuccessDetail"
                    }
                },
                "status": {
                    "type": "integer"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "msggateway.SingleDetail": {
            "type": "object",
            "properties": {
                "singlePlatformToken": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/msggateway.SinglePlatformToken"
                    }
                },
                "status": {
                    "type": "integer"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "msggateway.SinglePlatformToken": {
            "type": "object",
            "properties": {
                "platformID": {
                    "type": "integer"
                },
                "token": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "sdkws.GroupInfo": {
            "type": "object",
            "properties": {
                "applyMemberFriend": {
                    "type": "integer"
                },
                "createTime": {
                    "type": "integer"
                },
                "creatorUserID": {
                    "type": "string"
                },
                "ex": {
                    "type": "string"
                },
                "faceURL": {
                    "type": "string"
                },
                "groupID": {
                    "type": "string"
                },
                "groupName": {
                    "type": "string"
                },
                "groupType": {
                    "type": "integer"
                },
                "introduction": {
                    "type": "string"
                },
                "lookMemberInfo": {
                    "type": "integer"
                },
                "memberCount": {
                    "type": "integer"
                },
                "needVerification": {
                    "type": "integer"
                },
                "notification": {
                    "type": "string"
                },
                "notificationUpdateTime": {
                    "type": "integer"
                },
                "notificationUserID": {
                    "type": "string"
                },
                "ownerUserID": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "sdkws.GroupMemberFullInfo": {
            "type": "object",
            "properties": {
                "appMangerLevel": {
                    "description": "if \u003e0",
                    "type": "integer"
                },
                "ex": {
                    "type": "string"
                },
                "faceURL": {
                    "type": "string"
                },
                "groupID": {
                    "type": "string"
                },
                "inviterUserID": {
                    "type": "string"
                },
                "joinSource": {
                    "type": "integer"
                },
                "joinTime": {
                    "type": "integer"
                },
                "muteEndTime": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "operatorUserID": {
                    "type": "string"
                },
                "roleLevel": {
                    "type": "integer"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "sdkws.RequestPagination": {
            "type": "object",
            "properties": {
                "pageNumber": {
                    "type": "integer"
                },
                "showNumber": {
                    "type": "integer"
                }
            }
        },
        "sdkws.UserInfo": {
            "type": "object",
            "properties": {
                "appMangerLevel": {
                    "type": "integer"
                },
                "createTime": {
                    "type": "integer"
                },
                "ex": {
                    "type": "string"
                },
                "faceURL": {
                    "type": "string"
                },
                "globalRecvMsgOpt": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "third.AuthSignParts": {
            "type": "object",
            "properties": {
                "header": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/third.KeyValues"
                    }
                },
                "parts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/third.SignPart"
                    }
                },
                "query": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/third.KeyValues"
                    }
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "third.AuthSignReq": {
            "type": "object",
            "properties": {
                "partNumbers": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "uploadID": {
                    "type": "string"
                }
            }
        },
        "third.AuthSignResp": {
            "type": "object",
            "properties": {
                "header": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/third.KeyValues"
                    }
                },
                "parts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/third.SignPart"
                    }
                },
                "query": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/third.KeyValues"
                    }
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "third.CompleteMultipartUploadReq": {
            "type": "object",
            "properties": {
                "cause": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "uploadID": {
                    "type": "string"
                },
                "urlPrefix": {
                    "type": "string"
                }
            }
        },
        "third.CompleteMultipartUploadResp": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "third.InitiateMultipartUploadReq": {
            "type": "object",
            "properties": {
                "cause": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "maxParts": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "partSize": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "urlPrefix": {
                    "type": "string"
                }
            }
        },
        "third.InitiateMultipartUploadResp": {
            "type": "object",
            "properties": {
                "upload": {
                    "$ref": "#/definitions/third.UploadInfo"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "third.KeyValues": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "third.PartLimitReq": {
            "type": "object"
        },
        "third.PartLimitResp": {
            "type": "object",
            "properties": {
                "maxNumSize": {
                    "type": "integer"
                },
                "maxPartSize": {
                    "type": "integer"
                },
                "minPartSize": {
                    "type": "integer"
                }
            }
        },
        "third.PartSizeReq": {
            "type": "object",
            "properties": {
                "size": {
                    "type": "integer"
                }
            }
        },
        "third.PartSizeResp": {
            "type": "object",
            "properties": {
                "size": {
                    "type": "integer"
                }
            }
        },
        "third.SignPart": {
            "type": "object",
            "properties": {
                "header": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/third.KeyValues"
                    }
                },
                "partNumber": {
                    "type": "integer"
                },
                "query": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/third.KeyValues"
                    }
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "third.UploadInfo": {
            "type": "object",
            "properties": {
                "expireTime": {
                    "type": "integer"
                },
                "partSize": {
                    "type": "integer"
                },
                "sign": {
                    "$ref": "#/definitions/third.AuthSignParts"
                },
                "uploadID": {
                    "type": "string"
                }
            }
        },
        "user.GetPaginationUsersReq": {
            "type": "object",
            "properties": {
                "nickName": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/sdkws.RequestPagination"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "user.GetPaginationUsersResp": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sdkws.UserInfo"
                    }
                }
            }
        },
        "user.UserRegisterCountReq": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "integer"
                },
                "start": {
                    "type": "integer"
                }
            }
        },
        "user.UserRegisterCountResp": {
            "type": "object",
            "properties": {
                "before": {
                    "type": "integer"
                },
                "count": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:10002",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "飞宏IM接口",
	Description:      "飞宏IM接口",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
